### ISSUE TITLE
Unable to add calendars (from a Google account) to the app

### ISSUE THREAD

**Issue by Elderweiss-was-taken** [michalleptuch/calendar-flyout#28]
Before Microsoft disabled the native Calendar app, before Microsoft disabled the native Mail app, you were able to add a Gmail account and Yahoo account to both these Windows Store apps (Calendar & Mail)

Since Microsoft disabled these 2 apps, the only way to add a non Microsoft calendar (Yahoo account, Gmail account) is to go through the "new Outlook" app.

Calendar Flyout does not enable a support for the "new Outlook" app, but allows users to add the accounts directly to the Calendar Flyout app.

Which is good if you only use Microsoft accounts for the calendars, but if you used a Google or Yahoo account, then it is completely impossible for you to use them in Calendar Flyout.

Now I'm thanking the dev for updating the app to follow with the Microsoft new Outlook changes, now it's actually usable, but not for Google/Yahoo accounts.

**Comment by michalleptuch** [comment]
Hello, I will extend the available providers in the next releases of Calendar Flyout. I needed to focus on core functionalities and deliver them to the users as soon as possible because of broken mechanism of appointment syncing caused by changes in Microsoft's apps.

Thank you for your patience. 🙏

**Comment by anthonyg2003** [comment]
Until developer is able to add google/other calendars, a workaround is to go into your outlook web app (outlook.com - you probably already have a live.com, microsoft.com or outlook.com account since you're on windows). From the Outlook Web App > Calendar > Add Calendar > Subscribe from web. You'll want to grab the "ical" link from your google calendar to paste there. If your google calendar isn't public, you'll need to grab the "secret link".  Biggest problem is that OWA doesn't update subscriptions instantly, supposedly is usually every 3 hours, but can be as long as 24 hours between updates. 

https://support.microsoft.com/en-us/office/see-your-google-calendar-in-outlook-c1dab514-0ad4-4811-824a-7d02c5e77126

Not sure what the process for yahoo calendars is, but probably similar to google.

**Comment by hypedcolee7881** [comment]
Do you have an update on adding Google calendar accounts?

Half my calendar entries are in my google account, so until this is fixed, Calendar Flyout is quite unusable for me unfortunately. :(

**Comment by Aviv943** [comment]
Any update? All my calendars are in my Google account. The Calendar Flyout is useless for me now.

**Comment by michalleptuch** [comment]
Update: I'm waiting for Google to verify my application.

**Comment by hypedcolee7881** [comment]
Awesome! Can't wait for the Google calendar accounts to be accessible again :)

**Comment by kutukcu** [comment]
Great news.

**Comment by hypedcolee7881** [comment]
Any news?

**Comment by catagris** [comment]
Thank you for the nice app @michalleptuch, this is the feature I can't wait to have. :D

**Comment by Tomkov1c** [comment]
@michalleptuch When can we expect the 2.1 update. Love the app btw

**Comment by michalleptuch** [comment]
Hi, I'm working hard to finish the update and release it as soon as possible. 
No ETA for today, but I will inform you by next weekend.

**Comment by michalleptuch** [comment]
Okay, I can share some details and the current status of the update.

1. Google wants me to create an official and professional webpage for Calendar Flyout in order to approve and enable my app. This is a blocker, but I'm finishing this website and will be resuming the process tomorrow or Monday.

2. I need to address two bugs (critical: https://github.com/michalleptuch/calendar-flyout/issues/37, and medium: https://github.com/michalleptuch/calendar-flyout/issues/45), and I'm still considering releasing fixes before Calendar Flyout 2.1.

3. After Google's approval, I need to perform final tests on Calendar Flyout 2.1. I don't know of any other requirements in the approval process, so it's hard to say if this is the last step before pushing my app to the Store.

4. I need to add and test one more language.

**Comment by boccafos** [comment]
Hi, any news?

**Comment by Elderweiss-was-taken** [comment]
> Hi, any news?

@boccafos if you really want to get mad, then get mad when the dev doesn't deliver on his status update.

It's even just amazing that people like him take the time to do what a multi billion dollar company (Microsoft) can't do themselves.

Hopefully he delivers before december. Don't forget the app is just something like 3€ when he could easily charge more.

**Comment by boccafos** [comment]
@Elderweiss-was-taken I wasn't mad at all, I just wanted to know if something changed without rushing anyone. For instance I can't use the app now beacuse i only use Google calendar but i supported the developer anyway buiyng the license 'cause i believe in what he is doing.

**Comment by michalleptuch** [comment]
I completely understand the situation, but please keep in mind that I’m just a single developer. Developing Windows apps is not my full-time job, but I still try to find time for Calendar Flyout and my other apps whenever I can.

Please understand that I need to maintain a healthy work-life balance. Calendar Flyout is particularly challenging due to Microsoft discontinuing the Windows Appointment API and abandoning Mail and Calendar. Now I have to learn a lot, rebuild everything from scratch, and ensure that your events are secure, dates are correct, and all the necessary details are in place. Testing Google Calendar integration isn’t easy either, but the code base is ready, and I hope to enable the “Add Google account” button very soon.

I understand if you’re frustrated, but please remember—I’m not Microsoft. I’m just one person doing my best.

Thanks.

**Comment by Latisha19** [comment]
Thanks for that!!! I can finally buy it. Use with happy!
